server:
  port: 80

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    create: true
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
